name: Workflows 

on:
    push:
    workflow_dispatch:

env:
  API_ID: 15645529
  API_HASH: 'ebce16047fc49dc1347db6366a30bf86'
  BOT_TOKEN: '5027731817:AAEdVdwm2ljYDaGqDJc8iOv-iWkwqerrTGs'


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GitHubName }}
           git config --global user.email ${{ secrets.GitHubMail }}
           git config --global credential.helper store
           echo "https://creator-noob:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
           
       
       - name: cloning repo
         continue-on-error: true
         run: |
           git clone -b main https://creator-noob:${{ secrets.GH_TOKEN }}@github.com/creator-noob/Pyronoob.git
       - name: Running PrivateEncoderV2.0 Bot 
         timeout-minutes: 350
         continue-on-error: true
         run: |
           cd Pyronoob
           docker build -t dockerfiles . && docker run dockerfiles
           
       - name: Loop workflow
         continue-on-error: true
         run: |
           git clone https://${{ secrets.GH_TOKEN }}@github.com/${REPOSITORY} loop
           cd loop || exit 1
           echo $(( RANDOM - ( RANDOM % RANDOM ) )) > looper.txt
           git add looper.txt
           git commit -m "Workflow : Loop at $(date -u +%D-%T%P)"
           git push -q https://${{ secrets.GH_TOKEN }}@github.com/${REPOSITORY} HEAD:main
